import '../style/globals.css'
import { Montserrat } from 'next/font/google'

const inter = Montserrat({weight:"400",subsets:["latin"]});

export const metadata = {
  title: 'Create Next App',
  description: 'Generated by create next app',
}

export default function RootLayout({
  children,
}: {
  children: React.ReactNode
}) {
  return (
    <html lang="en" className='scroll-smooth'>
      <body className={inter.className}>{children}</body>
    </html>
  )
}
